application: susm
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /user/.*
  script: handler_user.py

- url: .*
  script: handler_home.py
